global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_protocols:
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusText0.0.4
scrape_configs:
  - job_name: 'microservice-prometheus'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.7.77:8008']
