version: '3.3'
services:
  howToDev-monitoring-prometheus:
    container_name: howToDev-monitoring-prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
  howToDev-monitoring-grafana:
    container_name: howToDev-monitoring-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456
      - GF_SECURITY_ADMIN_USER=admin

