#readMe: application.yml

server:
  port: 8012
---
management:
  tracing:
    sampling:
      probability: 1.0
---
spring:
  cloud:
    openfeign:
      oauth2:
        # clientRegistrationId must be some in spring.security.oauth2.client.{registration,provider}
        clientRegistrationId: my-microservice-openfeign-regId
        enabled: true
      # to support FeignContentGzipEncodingInterceptor
      compression:
        request:
          enabled: true
          mime-types: text/xml, application/xml, application/json
          min-request-size: 2048
        response:
          enabled: true
---
spring:
  security:
    oauth2:
      client:
        registration:
          my-microservice-openfeign-regId:
            authorization-grant-type: client_credentials
            client-id: my-microservice-openfeign
            client-secret: LUxRZtb7Bpq4bu3gYHqNOb2DRJPlLwUT
        provider:
          my-microservice-openfeign-regId:
            token-uri: http://localhost:8008/auth/realms/myRealm/protocol/openid-connect/token
---
#only to handle authorization on myself controllers(like my OrderController).
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8008/auth/realms/myRealm
---
myFeign:
  rest-servers:
    spring-tracer-producer-webserver:
      url: "http://localhost:8011"
---
logging:
  level:
    org.springframework.security: INFO #TRACE
    org.springframework: INFO #DEBUG

