spring:
  kafka:
    listener:
      ack-mode: manual
    consumer:
      bootstrap-servers: localhost:9096 #This is mandatory
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #This is mandatory
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #This is mandatory
    producer:
      bootstrap-servers: localhost:9096 #This is mandatory
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #This is mandatory
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #This is mandatory
    admin:
      properties:
        bootstrap.servers: localhost:9096
