#cu - kafka application settings - local profile
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9093,localhost:9094,localhost:9095 #This is mandatory
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #This is mandatory
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #This is mandatory
      group-id: springboot-kafka-consumer-annotated #This is mandatory

    admin:
      properties:
        bootstrap.servers: localhost:9093,localhost:9094,localhost:9095
