
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3007/liquibase?createDatabaseIfNotExist=true&serverTimezone=UTC
    &character_set_server=utf8mb4&useSSL=false&nullNamePatternMatchesAll=true&rewriteBatchedStatements=true"
    username: "root"
    password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: validate
  properties:
    hibernate:
      format_sql: true
  liquibase:
    enabled: true
---
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework: DEBUG


