plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

// Limit JVM memory and CPU usage
tasks.withType(JavaExec) {
    jvmArgs = [
        '-Xms512m', // Set initial heap size to 512 MB
        '-Xmx512m', // Set maximum heap size to 1024 MB
        '-XX:ActiveProcessorCount=1' // Limit JVM to use 2 CPU cores
    ]
}